"""AI-generated 来週の展望 (next-week market outlook) for US / JP markets.

毎週土曜(バックアップ: 日曜)に実行し、当週の市場データを集約して
Claude に「来週の展望」を書かせる。

Inputs (all pre-generated by other batches):
  - web/data/indices.json            — N225 / NDX / USDJPY + テクニカル指標
  - web/data/momentum_us.json        — US market_indicators (VIX / Fear&Greed) + top movers
  - web/data/momentum_jp.json        — JP market_indicators + top movers
  - web/data/nikkei_eps_history.json — 日経平均 EPS / PER 水準判定

Output: web/data/weekly_outlook.json
  {
    "asof": "YYYY-MM-DD",              # 直近の米国営業日 (momentum_us の asof)
    "week_start": "YYYY-MM-DD",        # 来週月曜
    "week_end": "YYYY-MM-DD",          # 来週金曜
    "generated_at_jst": "...",
    "model": "...",
    "one_liner": "来週の一言まとめ",
    "us": {"review": "...", "outlook": "...", "watch_points": ["..."]},
    "jp": {"review": "...", "outlook": "...", "watch_points": ["..."]},
    "fx": {"outlook": "..."},
    "key_events": [{"timing": "7/29(水)", "event": "...", "note": "..."}],
    "risks": ["..."]
  }

Requires env var: ANTHROPIC_API_KEY
Optional env var: WEEKLY_OUTLOOK_MODEL (default: claude-haiku-4-5-20251001)

Usage:
  python batch/generate_weekly_outlook.py            # generate + write JSON
  python batch/generate_weekly_outlook.py --dry-run  # print prompt only (no API call)
"""

from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "web" / "data"
OUT_PATH = DATA_DIR / "weekly_outlook.json"

MODEL = os.environ.get("WEEKLY_OUTLOOK_MODEL", "claude-haiku-4-5-20251001")
MAX_TOKENS = 4000

JST = timezone(timedelta(hours=9))


def _load(name: str) -> dict:
    p = DATA_DIR / name
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001
        print(f"WARN: failed to load {name}: {e}", file=sys.stderr)
        return {}


def _next_week_range(today: datetime) -> tuple[str, str]:
    """次の月曜〜金曜 (JST 基準)。土曜実行なら+2日、日曜なら+1日。
    月曜〜金曜に実行された場合は「当週の月曜〜金曜」を返す(週中の再実行対策)。"""
    if today.weekday() >= 5:  # Sat / Sun → 来週
        monday = today + timedelta(days=7 - today.weekday())
    else:  # 平日 → 当週(生成済み展望の対象週と一致させる)
        monday = today - timedelta(days=today.weekday())
    friday = monday + timedelta(days=4)
    return monday.strftime("%Y-%m-%d"), friday.strftime("%Y-%m-%d")


def _fmt_indices(ix: dict) -> str:
    lines = []
    for idx in ix.get("indices", []):
        name = idx.get("label") or idx.get("id")
        cur = idx.get("current") or {}
        ind = idx.get("indicators") or {}
        parts = [f"{name}: {cur.get('value')} (前日比 {cur.get('change_pct')}%)"]
        for k, label in (
            ("rsi14", "RSI14"),
            ("trend", "トレンド"),
            ("macd_phase", "MACD"),
            ("pct_from_sma200", "200日線乖離%"),
            ("bb_position_pct", "BB位置%"),
            ("atr_pct", "ATR%"),
        ):
            v = ind.get(k)
            if v is not None:
                parts.append(f"{label}:{v}")
        lines.append(" / ".join(str(x) for x in parts))
    for c in ix.get("correlations", []) or []:
        a, b, v = c.get("a"), c.get("b"), c.get("value")
        if a and b and v is not None:
            lines.append(f"相関 {a}-{b} ({c.get('period_days')}日): {v}")
    return "\n".join(lines) if lines else "(指数データなし)"


def _fmt_market(mom: dict, label: str) -> str:
    mi = mom.get("market_indicators") or {}
    lines = [f"asof: {mom.get('asof')}"]
    vix = mi.get("vix") or {}
    if vix:
        lines.append(f"VIX: {vix.get('value')} ({vix.get('level')}, 前日比 {vix.get('change_pct')}%)")
    fg = mi.get("fear_greed") or {}
    if fg:
        lines.append(f"Fear&Greed: {fg.get('score')} ({fg.get('label_ja') or fg.get('label')})")
    for key, name in (("yesterday_top10", "直近上昇TOP"), ("mom_1w_top10", "1週モメンタムTOP")):
        rows = (mom.get(key) or [])[:5]
        if rows:
            s = ", ".join(f"{r.get('ticker')}({r.get('name','')[:12]}) {r.get('value'):+.1f}%"
                          for r in rows if isinstance(r.get("value"), (int, float)))
            lines.append(f"{name}5: {s}")
    return f"【{label}】\n" + "\n".join(lines)


def _fmt_nikkei_eps(eps: dict) -> str:
    hist = eps.get("history") or []
    latest = hist[-1] if hist else {}
    parts = []
    if latest:
        parts.append(
            f"日経平均 直近({latest.get('date')}): 終値{latest.get('close')}"
            f" 加重PER{latest.get('per_weighted')} 加重EPS{latest.get('eps_weighted')}"
        )
    lj = eps.get("level_judgment") or {}
    if isinstance(lj, dict) and lj.get("label"):
        parts.append(f"バリュエーション判定: {lj.get('label')}")
    elif isinstance(lj, str) and lj:
        parts.append(f"バリュエーション判定: {lj}")
    return "\n".join(parts) if parts else "(EPSデータなし)"


def build_prompt(week_start: str, week_end: str, ix: dict, mom_us: dict, mom_jp: dict, eps: dict) -> str:
    today = datetime.now(JST).strftime("%Y-%m-%d (%a)")
    return f"""あなたは日本の個人投資家向け投資教育サイトの市場アナリストです。
以下の実データをもとに、来週({week_start}〜{week_end})の米国株・日本株の展望を書いてください。

本日: {today}

---指数モニター(実データ)---
{_fmt_indices(ix)}

---米国市場(実データ)---
{_fmt_market(mom_us, 'US: Russell 3000')}

---日本市場(実データ)---
{_fmt_market(mom_jp, 'JP: 東証プライム')}

---日経平均バリュエーション(実データ)---
{_fmt_nikkei_eps(eps)}

【執筆ルール】
- 上記の実データの数値を必ず引用して論拠にすること(データにない数値を捏造しない)
- 経済指標・イベントの日程は、確度の高い定例スケジュール(FOMC・日銀会合・米雇用統計・CPI・主要決算シーズン等)のみ挙げ、日付が不確かなものは「予定要確認」と付記
- 断定を避け、強気/弱気の両シナリオの分岐条件(価格水準・指標値)を示す
- 投資勧誘ではなく教育目的。最後に免責を意識した中立的なトーンで

【出力形式】必ず ```json と ``` で囲んだ JSON オブジェクトのみを返す:
{{
  "one_liner": "来週の相場を一言で(40字以内)",
  "us": {{
    "review": "今週の米国市場の振り返り(150〜250字、実データの数値引用)",
    "outlook": "来週の米国市場の展望(200〜350字、強気/弱気の分岐条件を含む)",
    "watch_points": ["注目ポイント1(価格水準や指標値を含む)", "注目ポイント2", "注目ポイント3"]
  }},
  "jp": {{
    "review": "今週の日本市場の振り返り(150〜250字)",
    "outlook": "来週の日本市場の展望(200〜350字)",
    "watch_points": ["注目ポイント1", "注目ポイント2", "注目ポイント3"]
  }},
  "fx": {{ "outlook": "ドル円の来週の見方(100〜200字、日本株への影響を含む)" }},
  "key_events": [
    {{ "timing": "例: 7/29(水)", "event": "イベント名", "note": "何が注目か・不確かなら『予定要確認』" }}
  ],
  "risks": ["リスク要因1", "リスク要因2", "リスク要因3"]
}}"""


JSON_BLOCK_RE = re.compile(r"```json\s*([\s\S]+?)\s*```", re.IGNORECASE)


def parse_outlook(text: str) -> dict:
    m = JSON_BLOCK_RE.search(text)
    candidate = m.group(1).strip() if m else text.strip().strip("`").strip()
    if candidate.startswith("json"):
        candidate = candidate[4:].strip()
    try:
        parsed = json.loads(candidate)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError as e:
        print(f"WARN: weekly outlook JSON parse failed: {e}", file=sys.stderr)
    return {}


def main() -> int:
    dry_run = "--dry-run" in sys.argv

    ix = _load("indices.json")
    mom_us = _load("momentum_us.json")
    mom_jp = _load("momentum_jp.json")
    eps = _load("nikkei_eps_history.json")

    if not mom_us and not mom_jp:
        print("ERROR: momentum data not found — run daily batches first", file=sys.stderr)
        return 1

    now = datetime.now(JST)
    week_start, week_end = _next_week_range(now)
    prompt = build_prompt(week_start, week_end, ix, mom_us, mom_jp, eps)

    if dry_run:
        print(prompt)
        return 0

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
        return 1

    import anthropic  # deferred import so --dry-run works without the package

    client = anthropic.Anthropic(api_key=api_key)
    print(f"Calling Claude ({MODEL}) for weekly outlook...", file=sys.stderr)
    resp = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        messages=[{"role": "user", "content": prompt}],
    )
    text = "".join(b.text for b in resp.content if b.type == "text").strip()
    outlook = parse_outlook(text)
    if not outlook or not outlook.get("us") or not outlook.get("jp"):
        print("ERROR: could not parse a complete outlook from model output", file=sys.stderr)
        print(text[:2000], file=sys.stderr)
        return 1
    print(
        f"Tokens: in={resp.usage.input_tokens} out={resp.usage.output_tokens}",
        file=sys.stderr,
    )

    output = {
        "asof": mom_us.get("asof") or mom_jp.get("asof"),
        "week_start": week_start,
        "week_end": week_end,
        "generated_at_jst": now.isoformat(),
        "model": MODEL,
        **outlook,
    }
    OUT_PATH.write_text(json.dumps(output, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {OUT_PATH}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
